apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvYWNjZXNzLXRva2VuIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxL3JlZnJlc2gtdG9rZW4iOiB7fSwKCQkiZ2hjci5pbyI6IHsKICAgICAJCQkiYXV0aCI6ICJiMjVrY25saE9tZG9jRjlvWTFOMFEwNTBiRFJ6T1ZCdFRFVkVZbU5YYWpsM1lsZzRUMWw1TkRBemExSlhWMVE9IgogICAgCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcC5leGUiCn0K
type: kubernetes.io/dockerconfigjson
